#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ASSET_DIR="${CY_ASSET_DIR:-$SCRIPT_DIR}"

CY_HOME="${CY_HOME:-$HOME/.cy}"
PORT="${CY_BRIDGE_PORT:-8790}"
mkdir -p "$CY_HOME"

AUTH_FILE="$CY_HOME/auth.json"
CONFIG="$CY_HOME/config.toml"

CY_BIN=""
for candidate in "$ASSET_DIR/cy" "$ASSET_DIR/bin/cy" "$HOME/.local/share/cy/bin/cy"; do
  if [ -x "$candidate" ]; then
    CY_BIN="$candidate"
    break
  fi
done
if [ -z "$CY_BIN" ]; then
  CY_BIN="$(command -v cy 2>/dev/null || true)"
fi
if [ -z "$CY_BIN" ]; then
  echo "CY: cy binary not found. Run the install script first." >&2
  exit 1
fi

case "${1:-}" in
  --version|-V|--help|-h)
    exec "$CY_BIN" "$@"
    ;;
esac

BRIDGE=""
for candidate in "$ASSET_DIR/cy_bridge.py" "$SCRIPT_DIR/cy_bridge.py" "$SCRIPT_DIR/../packaging/bridge/cy_bridge.py" "$SCRIPT_DIR/../packaging/macos/cy_bridge.py"; do
  if [ -f "$candidate" ]; then
    BRIDGE="$(cd "$(dirname "$candidate")" && pwd)/$(basename "$candidate")"
    break
  fi
done

AUTH_SERVER=""
for candidate in "$ASSET_DIR/cy_auth_server.py" "$SCRIPT_DIR/cy_auth_server.py" "$SCRIPT_DIR/../packaging/bridge/cy_auth_server.py" "$SCRIPT_DIR/../packaging/macos/cy_auth_server.py"; do
  if [ -f "$candidate" ]; then
    AUTH_SERVER="$(cd "$(dirname "$candidate")" && pwd)/$(basename "$candidate")"
    break
  fi
done

port_open() {
  bash -c "exec 3<>/dev/tcp/127.0.0.1/$PORT" 2>/dev/null
}

start_bridge() {
  if port_open; then
    return
  fi
  if [ -z "$BRIDGE" ] || [ ! -f "$BRIDGE" ]; then
    echo "  CY bridge is missing." >&2
    exit 1
  fi
  PYTHON="$(command -v python3 || true)"
  if [ -z "$PYTHON" ]; then
    echo "  CY requires python3." >&2
    exit 1
  fi
  CY_API_BASE_URL="${CY_API_BASE_URL:-https://cy.symbiotyc.workers.dev/v1}" \
  CY_BRIDGE_PORT="$PORT" \
  CY_HOME="$CY_HOME" \
  CY_API_KEY="$KEY" \
  nohup "$PYTHON" "$BRIDGE" >"$CY_HOME/bridge.log" 2>&1 &
  disown 2>/dev/null || true
  for _ in $(seq 1 50); do
    if port_open; then
      return
    fi
    sleep 0.1
  done
  echo "  CY bridge did not become ready on port $PORT." >&2
  exit 1
}

read_key() {
  python3 - "$AUTH_FILE" <<'PY' 2>/dev/null || true
import json
import sys

try:
    with open(sys.argv[1], encoding="utf-8") as handle:
        data = json.load(handle)
except Exception:
    raise SystemExit
for field in ("cy_api_key", "CY_API_KEY"):
    value = data.get(field) if isinstance(data, dict) else None
    if isinstance(value, str) and value.strip():
        print(value.strip())
        break
PY
}

KEY="${CY_API_KEY:-}"
if [ -z "$KEY" ]; then
  KEY="$(read_key | tr -d '[:space:]')"
else
  KEY="$(printf '%s' "$KEY" | tr -d '[:space:]')"
fi
if [ -n "$KEY" ]; then
  # Persist the resolved key and pass it explicitly to the terminal session.
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$AUTH_FILE" "$KEY" <<'PY' >/dev/null 2>&1 || true
import json
import os
import sys

path, key = sys.argv[1], sys.argv[2]
try:
    with open(path, encoding="utf-8") as handle:
        data = json.load(handle)
except Exception:
    data = {}
if not isinstance(data, dict):
    data = {}
data.update({"auth_mode": "apiKey", "cy_api_key": key, "CY_API_KEY": key})
with open(path, "w", encoding="utf-8") as handle:
    json.dump(data, handle, indent=2)
os.chmod(path, 0o600)
PY
  fi
  export CY_API_KEY="$KEY"
  start_bridge
fi

cat > "$CONFIG" <<EOF
# CY Config - generated by CY-CLI launcher
model = "cy/i1a"
model_provider = "cy"
model_context_window = 128000
model_auto_compact_token_limit = 96000
model_reasoning_summary = "auto"
model_reasoning_effort = "none"
approval_policy = "never"
EOF

THEMES_SRC="$ASSET_DIR/themes"
THEMES_DST="$CY_HOME/themes"
if [ -d "$THEMES_SRC" ]; then
  mkdir -p "$THEMES_DST"
  for theme in "$THEMES_SRC"/*.tmTheme; do
    [ -f "$theme" ] || continue
    name="$(basename "$theme")"
    if [ ! -f "$THEMES_DST/$name" ]; then
      cp "$theme" "$THEMES_DST/$name"
    fi
  done
fi

ESC=$'\033'
PINK="${ESC}[1;35m"
CYAN="${ESC}[1;36m"
DIM="${ESC}[2;37m"
RESET="${ESC}[0m"

SPLASH_FILE="$CY_HOME/.splash.ansi"
cat > "$SPLASH_FILE" <<SPLASH_EOF
${PINK}
  ██████╗██╗   ██╗
 ██╔════╝╚██╗ ██╔╝
 ██║      ╚████╔╝
 ██║       ╚██╔╝
 ╚██████╗   ██║
  ╚═════╝   ╚═╝${RESET}

 ${PINK}CY${RESET} ${DIM}CLI${RESET}
 ${DIM}Loading TUI...${RESET}
SPLASH_EOF

INNER="$CY_HOME/.cy_launch.sh"
export CY_BIN BRIDGE AUTH_SERVER CY_HOME AUTH_FILE PORT SPLASH_FILE INNER
cat > "$INNER" <<'INNER_EOF'
#!/usr/bin/env bash
set -euo pipefail

cleanup() {
  rm -f "$SPLASH_FILE" "$INNER"
}
trap cleanup EXIT

export CX_HOME="$CY_HOME"
export CODEX_HOME="$CY_HOME"
export CY_HOME="$CY_HOME"
export CY_BASE_URL="http://127.0.0.1:$PORT/v1"

read_key() {
  python3 - "$AUTH_FILE" <<'PY' 2>/dev/null || true
import json
import sys

try:
    with open(sys.argv[1], encoding="utf-8") as handle:
        data = json.load(handle)
except Exception:
    raise SystemExit
for field in ("cy_api_key", "CY_API_KEY"):
    value = data.get(field) if isinstance(data, dict) else None
    if isinstance(value, str) and value.strip():
        print(value.strip())
        break
PY
}

clear
cat "$SPLASH_FILE"
echo ""

KEY="${CY_API_KEY:-}"
if [ -z "$KEY" ]; then
  KEY="$(read_key | tr -d '[:space:]')"
fi
if [ -z "$KEY" ]; then
  printf '  Sign in with Google? [Y/n] '
  if ! read -r ANSWER; then
    exit 1
  fi
  case "$ANSWER" in
    [nN]*)
      echo ""
      echo "  CY needs an API key to work. Launch CY again when ready."
      read -r -p "  Press Enter to close... " _
      exit 1
      ;;
  esac
  if [ -z "$AUTH_SERVER" ] || [ ! -f "$AUTH_SERVER" ]; then
    echo "  CY authorization helper is missing." >&2
    exit 1
  fi
  echo ""
  echo "  Opening browser — sign in with Google, the key saves automatically..."
  python3 "$AUTH_SERVER"
  KEY="$(read_key | tr -d '[:space:]')"
  if [ -z "$KEY" ]; then
    echo ""
    echo "  Sign-in did not complete. Launch CY again to retry."
    read -r -p "  Press Enter to close... " _
    exit 1
  fi
  echo "  Signed in. Starting CY..."
  sleep 1
fi

export CY_API_KEY="$KEY"

if ! port_open; then
  if [ -z "$BRIDGE" ] || [ ! -f "$BRIDGE" ]; then
    echo "  CY bridge is missing." >&2
    exit 1
  fi
  PYTHON="$(command -v python3 || true)"
  if [ -z "$PYTHON" ]; then
    echo "  CY requires python3." >&2
    exit 1
  fi
  CY_API_BASE_URL="${CY_API_BASE_URL:-https://cy.symbiotyc.workers.dev/v1}" \
  CY_BRIDGE_PORT="$PORT" \
  CY_HOME="$CY_HOME" \
  CY_API_KEY="$KEY" \
  nohup "$PYTHON" "$BRIDGE" >"$CY_HOME/bridge.log" 2>&1 &
  disown 2>/dev/null || true
  for _ in $(seq 1 50); do
    if port_open; then
      break
    fi
    sleep 0.1
  done
fi

cd "$HOME"
exec "$CY_BIN" "$@"
INNER_EOF
chmod +x "$INNER"

if [ "${CY_LAUNCH_INLINE:-}" = "1" ]; then
  bash "$INNER" "$@"
  exit $?
fi

if command -v x-terminal-emulator >/dev/null 2>&1; then
  x-terminal-emulator -e bash "$INNER" "$@" >/dev/null 2>&1 &
elif command -v gnome-terminal >/dev/null 2>&1; then
  gnome-terminal -- bash "$INNER" "$@" >/dev/null 2>&1 &
elif command -v konsole >/dev/null 2>&1; then
  konsole -e bash "$INNER" "$@" >/dev/null 2>&1 &
elif command -v xfce4-terminal >/dev/null 2>&1; then
  xfce4-terminal -e "bash \"$INNER\" $*" >/dev/null 2>&1 &
elif command -v xterm >/dev/null 2>&1; then
  xterm -e bash "$INNER" "$@" >/dev/null 2>&1 &
else
  echo "CY: no terminal emulator found; launching in the current terminal." >&2
  bash "$INNER" "$@"
fi
