$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$AssetDir = if ($env:CY_ASSET_DIR) { $env:CY_ASSET_DIR } else { $ScriptDir }
$CyHome = if ($env:CY_HOME) { $env:CY_HOME } else { Join-Path $env:USERPROFILE '.cy' }
$Port = if ($env:CY_BRIDGE_PORT) { [int]$env:CY_BRIDGE_PORT } else { 8790 }
New-Item -ItemType Directory -Force -Path $CyHome | Out-Null

$AuthFile = Join-Path $CyHome 'auth.json'
$Config = Join-Path $CyHome 'config.toml'

function Find-CyBin {
    $candidates = @(
        (Join-Path $AssetDir 'cy.exe'),
        (Join-Path $AssetDir 'bin\cy.exe'),
        (Join-Path $env:USERPROFILE '.local\share\cy\bin\cy.exe')
    )
    foreach ($candidate in $candidates) {
        if (Test-Path $candidate) { return $candidate }
    }
    foreach ($name in @('cy.exe', 'cy')) {
        $command = Get-Command $name -ErrorAction SilentlyContinue
        if ($command) { return $command.Source }
    }
    return $null
}

function Find-Script {
    param([string]$Name)

    $candidates = @(
        (Join-Path $AssetDir $Name),
        (Join-Path $ScriptDir $Name),
        (Join-Path $ScriptDir "..\packaging\bridge\$Name"),
        (Join-Path $ScriptDir "..\packaging\macos\$Name")
    )
    foreach ($candidate in $candidates) {
        if (Test-Path $candidate) { return (Resolve-Path $candidate).Path }
    }
    return $null
}

function Test-Port {
    param([int]$Number)

    try {
        $client = New-Object System.Net.Sockets.TcpClient
        $client.Connect('127.0.0.1', $Number)
        $client.Close()
        return $true
    } catch {
        return $false
    }
}

function Read-CyKey {
    if ($env:CY_API_KEY -and $env:CY_API_KEY.Trim()) {
        return $env:CY_API_KEY.Trim()
    }
    if (-not (Test-Path $AuthFile)) {
        return $null
    }
    try {
        $data = Get-Content $AuthFile -Raw | ConvertFrom-Json
        foreach ($field in @('cy_api_key', 'CY_API_KEY')) {
            $value = $data.$field
            if ($value -is [string] -and $value.Trim()) {
                return $value.Trim()
            }
        }
    } catch { }
    return $null
}

function Write-CyAuth {
    param([string]$Key)

    $data = if (Test-Path $AuthFile) {
        try { Get-Content $AuthFile -Raw | ConvertFrom-Json } catch { [ordered]@{} }
    } else {
        [ordered]@{}
    }
    if ($null -eq $data -or $data -isnot [pscustomobject]) {
        $data = [ordered]@{}
    }
    $data.auth_mode = 'apiKey'
    $data.cy_api_key = $Key
    $data.CY_API_KEY = $Key
    $data | ConvertTo-Json -Depth 10 | Set-Content -Path $AuthFile -Encoding UTF8
}

function Find-Python {
    foreach ($name in @('python.exe', 'python3.exe', 'py.exe')) {
        $command = Get-Command $name -ErrorAction SilentlyContinue
        if ($command) { return $command.Source }
    }
    return $null
}

function Start-CyBridge {
    param([string]$Key)

    if (Test-Port $Port) { return }
    if (-not $Bridge) { Write-Error 'CY: cy_bridge.py not found.' }
    $python = Find-Python
    if (-not $python) { Write-Error 'CY: python.exe, python3.exe, or py.exe not found.' }

    $env:CY_API_BASE_URL = if ($env:CY_API_BASE_URL) { $env:CY_API_BASE_URL } else { 'https://cy.symbiotyc.workers.dev/v1' }
    $env:CY_BRIDGE_PORT = "$Port"
    $env:CY_HOME = $CyHome
    $env:CY_API_KEY = $Key

    $bridgeArgs = @()
    if ((Split-Path -Leaf $python) -eq 'py.exe') { $bridgeArgs += '-3' }
    $bridgeArgs += $Bridge
    Start-Process -FilePath $python -ArgumentList $bridgeArgs -WindowStyle Hidden
    for ($i = 0; $i -lt 50; $i++) {
        if (Test-Port $Port) { return }
        Start-Sleep -Milliseconds 100
    }
    Write-Error "CY: bridge did not become ready on port $Port."
}

$CyBin = Find-CyBin
if (-not $CyBin) {
    Write-Host 'CY: cy.exe not found. Run the install script first.' -ForegroundColor Red
    exit 1
}
if ($args.Count -gt 0 -and $args[0] -in @('--version', '-V', '--help', '-h')) {
    & $CyBin @args
    exit $LASTEXITCODE
}
$Bridge = Find-Script 'cy_bridge.py'
$AuthServer = Find-Script 'cy_auth_server.py'
$Key = Read-CyKey
if ($Key) {
    Write-CyAuth $Key
    $env:CY_API_KEY = $Key
    Start-CyBridge $Key
}

@"
# CY Config - generated by CY-CLI launcher
model = "cy/i1a"
model_provider = "cy"
model_context_window = 128000
model_auto_compact_token_limit = 96000
model_reasoning_summary = "auto"
model_reasoning_effort = "none"
approval_policy = "never"
"@ | Set-Content -Path $Config -Encoding UTF8

$ThemesSrc = Join-Path $AssetDir 'themes'
if (Test-Path $ThemesSrc) {
    $ThemesDst = Join-Path $CyHome 'themes'
    New-Item -ItemType Directory -Force -Path $ThemesDst | Out-Null
    Get-ChildItem -Path (Join-Path $ThemesSrc '*.tmTheme') -ErrorAction SilentlyContinue | ForEach-Object {
        $destination = Join-Path $ThemesDst $_.Name
        if (-not (Test-Path $destination)) { Copy-Item $_.FullName $destination }
    }
}

$esc = [string][char]27
$PINK = "${esc}[1;35m"
$DIM = "${esc}[2;37m"
$RESET = "${esc}[0m"
$SplashFile = Join-Path $CyHome '.splash.ansi'
$splash = @"
${PINK}
  ██████╗██╗   ██╗
 ██╔════╝╚██╗ ██╔╝
 ██║      ╚████╔╝
 ██║       ╚██╔╝
 ╚██████╗   ██║
  ╚═════╝   ╚═╝${RESET}

 ${PINK}CY${RESET} ${DIM}CLI${RESET}
 ${DIM}Loading TUI...${RESET}
"@
[IO.File]::WriteAllText($SplashFile, $splash, [Text.Encoding]::UTF8)

$Inner = Join-Path $CyHome '.cy_launch.ps1'
$env:CY_LAUNCH_CY_BIN = $CyBin
$env:CY_LAUNCH_BRIDGE = $Bridge
$env:CY_LAUNCH_AUTH_SERVER = $AuthServer
$env:CY_LAUNCH_CY_HOME = $CyHome
$env:CY_LAUNCH_AUTH_FILE = $AuthFile
$env:CY_LAUNCH_PORT = "$Port"
$env:CY_LAUNCH_SPLASH_FILE = $SplashFile
$innerBody = @'
$ErrorActionPreference = 'Stop'

$CyBin = $env:CY_LAUNCH_CY_BIN
$Bridge = $env:CY_LAUNCH_BRIDGE
$AuthServer = $env:CY_LAUNCH_AUTH_SERVER
$CyHome = $env:CY_LAUNCH_CY_HOME
$AuthFile = $env:CY_LAUNCH_AUTH_FILE
$Port = [int]$env:CY_LAUNCH_PORT
$SplashFile = $env:CY_LAUNCH_SPLASH_FILE

function Read-Key {
    if ($env:CY_API_KEY -and $env:CY_API_KEY.Trim()) {
        return $env:CY_API_KEY.Trim()
    }
    if (-not (Test-Path $AuthFile)) { return $null }
    try {
        $data = Get-Content $AuthFile -Raw | ConvertFrom-Json
        foreach ($field in @('cy_api_key', 'CY_API_KEY')) {
            $value = $data.$field
            if ($value -is [string] -and $value.Trim()) { return $value.Trim() }
        }
    } catch { }
    return $null
}

function Find-Python {
    foreach ($name in @('python.exe', 'python3.exe', 'py.exe')) {
        $command = Get-Command $name -ErrorAction SilentlyContinue
        if ($command) { return $command.Source }
    }
    return $null
}

function Test-Port {
    try {
        $client = New-Object System.Net.Sockets.TcpClient
        $client.Connect('127.0.0.1', $Port)
        $client.Close()
        return $true
    } catch { return $false }
}

function Write-Auth {
    param([string]$Key)

    $data = if (Test-Path $AuthFile) {
        try { Get-Content $AuthFile -Raw | ConvertFrom-Json } catch { [ordered]@{} }
    } else {
        [ordered]@{}
    }
    if ($null -eq $data -or $data -isnot [pscustomobject]) {
        $data = [ordered]@{}
    }
    $data.auth_mode = 'apiKey'
    $data.cy_api_key = $Key
    $data.CY_API_KEY = $Key
    $data | ConvertTo-Json -Depth 10 | Set-Content -Path $AuthFile -Encoding UTF8
}

function Start-Bridge {
    param([string]$Key)

    if (Test-Port $Port) { return }
    if (-not $Bridge) { Write-Error 'CY: cy_bridge.py not found.' }
    $python = Find-Python
    if (-not $python) { Write-Error 'CY: python.exe, python3.exe, or py.exe not found.' }
    $env:CY_API_BASE_URL = if ($env:CY_API_BASE_URL) { $env:CY_API_BASE_URL } else { 'https://cy.symbiotyc.workers.dev/v1' }
    $env:CY_BRIDGE_PORT = "$Port"
    $env:CY_HOME = $CyHome
    $env:CY_API_KEY = $Key
    $bridgeArgs = @()
    if ((Split-Path -Leaf $python) -eq 'py.exe') { $bridgeArgs += '-3' }
    $bridgeArgs += $Bridge
    Start-Process -FilePath $python -ArgumentList $bridgeArgs -WindowStyle Hidden
    for ($i = 0; $i -lt 50; $i++) {
        if (Test-Port $Port) { return }
        Start-Sleep -Milliseconds 100
    }
    Write-Error "CY: bridge did not become ready on port $Port."
}

try {
    $env:CX_HOME = $CyHome
    $env:CODEX_HOME = $CyHome
    $env:CY_HOME = $CyHome
    $env:CY_BASE_URL = "http://127.0.0.1:$Port/v1"

    Clear-Host
    Get-Content $SplashFile
    Write-Host ''

    $Key = Read-Key
    if (-not $Key) {
        $answer = Read-Host '  Sign in with Google? [Y/n]'
        if ($answer -match '^[nN]') {
            Write-Host ''
            Write-Host '  CY needs an API key to work. Launch CY again when ready.'
            [Console]::ReadLine() | Out-Null
            exit 1
        }
        if (-not $AuthServer -or -not (Test-Path $AuthServer)) {
            Write-Error 'CY authorization helper is missing.'
        }
        Write-Host ''
        Write-Host '  Opening browser — sign in with Google, the key saves automatically...'
        $python = Find-Python
        if (-not $python) { Write-Error 'CY: python.exe, python3.exe, or py.exe not found.' }
        $authArgs = @()
        if ((Split-Path -Leaf $python) -eq 'py.exe') { $authArgs += '-3' }
        $authArgs += $AuthServer
        & $python @authArgs
        $Key = Read-Key
        if (-not $Key) {
            Write-Host ''
            Write-Host '  Sign-in did not complete. Launch CY again to retry.'
            [Console]::ReadLine() | Out-Null
            exit 1
        }
        Write-Auth $Key
        Write-Host '  Signed in. Starting CY...'
        Start-Sleep -Seconds 1
    }

    $env:CY_API_KEY = $Key
    Start-Bridge $Key
    $home = if ($env:USERPROFILE) { $env:USERPROFILE } else { $HOME }
    Set-Location $home
    & $CyBin @args
} finally {
    Remove-Item $SplashFile -Force -ErrorAction SilentlyContinue
    Remove-Item $MyInvocation.MyCommand.Path -Force -ErrorAction SilentlyContinue
}
'@
[IO.File]::WriteAllText($Inner, $innerBody, [Text.Encoding]::UTF8)

if ($env:CY_LAUNCH_INLINE -eq '1') {
    & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Inner @args
    exit $LASTEXITCODE
}

$quotedInner = '"' + $Inner.Replace('"', '\"') + '"'
$launcherArgs = @('powershell.exe', '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $quotedInner) + @args
$wt = Get-Command wt.exe -ErrorAction SilentlyContinue
if ($wt) {
    Start-Process wt.exe -ArgumentList $launcherArgs
} else {
    Start-Process powershell.exe -ArgumentList @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $quotedInner) + @args
}
